apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue1
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: blue1
  template:
    metadata:
      labels:
        app: myapp
        version: blue1
    spec:
      containers:
      - name: myapp
        image: gcr.io/noble-vine-394913/k8s-myapp1:blue1
        ports:
        - containerPort: 8888 