apiVersion: v1
kind: Service
metadata:
  name: myapp-blue-service
spec:
  selector:
    app: myapp
    version: blue1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-blue1-service
spec:
  selector:
    app: myapp
    version: blue1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
  type: LoadBalancer