apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress-1
spec:
  tls:
  - hosts:
    - altostrat.com
    secretName: my-web-server
          service:
            name: myapp-blue1
            port:
              number: 8888
